### ISSUE TITLE
Urlaubsberechnung von Heilig Abend und Silvester

### ISSUE THREAD

**Issue by simonschaufi** [itmastergmbh/SmallTime#12]
In meiner Firma ist es so, dass Heilig Abend ein halber Tag und Silvester ein halber Tag Urlaub berechnet wird. Diese Tage lassen sich aber bisher nur aktivieren oder deaktivieren.

**Comment by karu** [comment]
für eine kleine NGO möchte ich übergangsweise SmallTime einsetzen und benötige dazu nur die Möglichkeit, für einige Tage halbe Tage resp. eine Soll-Arbeitszeit von zum Beispiel 6h festzulegen - ist beim Format irgendwas angedacht?

**Comment by itmastergmbh** [comment]
Ich hab das im Moment immer mit einer Absenz gelöst, die zu Lasten der Firma geht.. (bei mir : I = Intern) (z. B. 8 Stunden soll nun auf 6, dann 0.25 Tage Intern als Absenz eintragen) 
Überzeit ist dann nicht mehr möglich (von der Logik her auch nicht schnell umsetzbar)

**Comment by karu** [comment]
ah, gute Idee - mal gucken, wenn ich es nicht hinkrieg gibt es wenigstens noch ne Möglichkeit

**Comment by karu** [comment]
es funktioniert / besteht Interesse, das für andere nutzbar zu machen (konfig settings?)

**Comment by mazeug** [comment]
Hallo, wie sieht die Lösung aus. Bei uns ist es auch so, dass 24. und 31. immer nur zur Hälfte frei sein. 
Zusätzlich hätte ich noch die Frage ob es möglich ist es einzustellen, dass Ferien immer nur zum Einstellungsdatum hinzugefügt werden und nicht zum Jahresbeginn.
LG

**Comment by itmastergmbh** [comment]
Salü, halbe Feiertage regle ich immer über eine Absenz (z.B. I = Intern und gib dann den Wert ein)
Ist zur Zeit auch nicht in Planung für eine Erweiterung.
Ferien nur bis zum Einstellungsdatum habe ich nicht abgefangen, ist auch noch nicht auf meiner Pendenzen-liste, würde sicher einer falschen Bedienung vorbeugen.

**Comment by thomasboehm** [comment]
Da der 24.12. und 31.12. immer auf den gleichen Wochentag fallen, habe ich das bei uns so "geloest": Der 31.12. wird als Feiertag in den Einstellungen festgelegt und der 24.12. bleibt voller Arbeitstag. Die mitarbeiter tragen dann am 24.12. einen Tag Urlaub ein und in der Summe am Monatsende stimmt dann alles wieder. Geht natuerlich nur, wenn die Firma an den Tagen wirklich geschlossen ist, sonst wird's komplizierter.
