### ISSUE TITLE
Arbeitszeiten über Mitternacht

### ISSUE THREAD

**Issue by peterbeck** [itmastergmbh/SmallTime#28]
Hallo zusammen,

ich habe SmallTime einem kleinen Restaurant mal zur Betrachtung installiert. Dort ist es üblich, dass man morgens jeweils ein paar Stunden und dann erst abends, meist bis nach Mitternacht arbeitet.
Wenn in Smalltime aber z.B. um 17.30 eingestempelt, aber erst um 01:30 des Folgetags ausgestempelt wird, diese Zeit dann als Einstempeln des Folgetages gezählt wird und am Vortag "fehlende Zeit" reklamiert wird. 

![screenshot from 2015-02-25 01 28 03](https://cloud.githubusercontent.com/assets/561186/6362454/969f9144-bc8d-11e4-8de2-83c77c8c6b22.png)

Gruss

**Comment by itmastergmbh** [comment]
Guten Tag Herr Beck,
Vermutlich kommen sie nicht um eine kostenpflichtige Version herum,  die 
das kann.

SmallTime berechnet die Stempelzeiten pro Tag.  Natürlich kann man über 
Nacht gearbeitet wählen (siehe Anleitungen) ,  aber die Zeiten von  0 bis 
1.30 würden dann beim nächsten Tag berechnet.

Das was Sie vermutlich brauchen benötigt im Hintergrund ganz eine andere 
Berechnung und ist mit SmallTime so nicht möglich.


Viele Grüsse
M.Heizmann



Am 25. Februar 2015 01:23:33 schrieb Peter Beck <notifications@github.com>:

**Comment by peterbeck** [comment]
Hallo Hr. Heinzmann,
danke fuer die Info. Das Issue kein meiner Meinung geschlossen werden..
Gruss
