### ISSUE TITLE
Saldo Monatsanfang / Monatsende stimmt nicht

### ISSUE THREAD

**Issue by krebbi** [itmastergmbh/SmallTime#29]
Ich hab hier bei einer Mitarbeiterin im Januar ein Monatsende-Salso von -3,76 und im Februar ein Monatsanfang-Saldo von 4,54 Stunden. 
Hat sonst noch wer sowas?

**Comment by itmastergmbh** [comment]
Ev. im Cache vom Browser eine alte PDF - Variante?
Die Dateien schon mal neu mit dem Druckersymbol erstellt und dann gespeichert auf dem Desktop und dann verglichen?

**Comment by krebbi** [comment]
genau das hatte ich gemacht. irgendwie scheint da der wurm drin zu sein...

**Comment by itmastergmbh** [comment]
ich glaube ich konnte das Problem nachvollziehen.
bei mir löste es sich folgendermassen:
Im Admin Januar neu ausgedruckt und dann rechte Maustaste -> neu laden.
Ein Download der PDF war auch immer falsch. (ich denke hat mit den Cache vom Browser zu tun)
Das gleiche mit Februar.
danke für Deine Rückmeldung

**Comment by krebbi** [comment]
nein, hilft nicht.. sollen wir per email weiter machen?

**Comment by itmastergmbh** [comment]
Falls Du die neuste Version hast....
Am 30. Oktober14 hab ich ein Problem mit den Berechnungen gefixt.
(https://github.com/itmastergmbh/SmallTime/commit/622bedacd9eb4dfe7c2ed7d751f7bc7014cf3a82)

Dann schick mir von der Mitarbeiterin das ZIP - File (im Admin kann direkt ein ZIP - File erstellt werden) Dann kann ich das anschauen und Dir eine Rückmeldung geben. (besser per mail: info@it-master.ch)
