### ISSUE TITLE
Klarstellung der Lizenz

### ISSUE THREAD

**Issue by mcdope** [itmastergmbh/SmallTime#30]
Auf der Website steht zwar das SmallTime Open-Source ist, das ist ja auch mehr oder weniger offensichtlich durch dieses Repo. 

Allerdings wird nirgendwo konkretisiert unter welcher Lizenz der Code nun steht, oder ich finde es nicht. GPL? BSD? Apache? AGPL?

**Comment by itmastergmbh** [comment]
Ich habe mich noch nicht in alle Details von den Lizenzen durchgearbeitet, aber sollte etwa so sein:

Small - Time darf kostenlos verwendet und weitergegeben werden. (egal ob Geschäftlich oder Privat) 

Wir bitten Sie, die Copyright-Vermerke nicht zu entfernen oder in irgendeiner Art abzudecken. 
(Copyright bleibt bei mir)

Erweiterungen sind auch OpenSource weiter zu geben und ebenfalls kostenlos für Private wie geschäftliche Zwecke. 

Ich hoffe das ist etwas das was Sie gesucht haben.

**Comment by mcdope** [comment]
Also kein Problem wenn ich eine unmodifizierte Variante in Kombination mit Dienstleistungen drum herum kommerziell vertreibe?

(Dabei ist aber übrigens geplant bei jedem Verkauf eine Spende zurückfließen zu lassen)

**Comment by itmastergmbh** [comment]
Sie verkaufen dann ja Ihre Dienste und geben SmallTime kostenlos ab. Das ist vergleichbar wie wenn ein Kunde Linux auf  einem PC möchte.  Betriebssystem ist Kostenlos,  das einrichten nicht. 

Das passt. 
Auch wenn ein Kunde spezielle Erweiterungen wünscht,  die speziell für ihn programmiert werden,  sehe ich kein Problem. (Das sind dann Entwicklungs -  Kosten die verrechnet werden dürfen) 

Falls Erweiterungen Programmiert werden,  die mehrfach eingesetzt werden möchten,  sind diese kostenlos,  das copyright bleibt dann beim jeweiligen Entwickler.

**Comment by mcdope** [comment]
Prima, das dachte ich mir. Wollte nur auf der sicheren Seite sein.

Danke für die Erläuterung.
