### ISSUE TITLE
Einstellungen für automatische Pausen ab einer Stempelzeit von X Stunden.

### ISSUE THREAD

**Issue by andre5tz** [itmastergmbh/SmallTime#31]
Hallo,
ich habe SmallTime erst kürzlich entdeckt und jetzt testen wir, ob SmallTime bei uns als "Stempeluhr" genutzt werden kann. Erst mal vorab ein herzliches Dankeschön für die Software und für die Bereitstellung. Wenn die Testphase erfolgreich verläuft drücken wir auch ganz sicher mal auf den Spenden-Button.

Mir ist beim Testen aufgefallen, dass die Einstellung für automatische Pausen, zumindest nach meinem Verständnis, nicht korrekt funktioniert. 
Die Einstellung lautet 6.0 unter Pause ab ? Stunden.

Nach meiner Vorstellung sollen nach 6 Stunden Arbeitszeit 30 Minuten Pause eingehalten werden, zumindest für Deutschland. 
>Arbeitszeitgesetz (ArbZG) § 4 Ruhepausen
Die Arbeit ist durch im voraus feststehende Ruhepausen von mindestens 30 Minuten bei einer Arbeitszeit von mehr als sechs bis zu neun Stunden und 45 Minuten bei einer Arbeitszeit von mehr als neun Stunden insgesamt zu unterbrechen. Die Ruhepausen nach Satz 1 können in Zeitabschnitte von jeweils mindestens 15 Minuten aufgeteilt werden. Länger als sechs Stunden hintereinander dürfen Arbeitnehmer nicht ohne Ruhepause beschäftigt werden.

Dies bedeutet für mich, dass nach 6 Stunden die nun folgenden 30 Minuten nicht als Arbeitszeit gerechnet werden dürfen, weil ja eine Pause einzuhalten ist. Vorherige Pausen von mindestens 15 Minuten wären auch noch zu berücksichtigen.
Das System zieht aber nach 6 Stunden automatisch 30 Minuten ab, somit entsteht ein Ist von 5,5 Std.
Arbeitet ein Mitarbeiter an einem Tag 6,25 Stunden, dann werden ihm 5,75 Std. eingetragen. Richtig wären aber in dem Fall 6,0 Stunden.

Weiter ist es möglich, die automatische Pausenregelung zu umgehen indem ich kurz vor Ablauf der eingestellen Zeit ausstempel und sofort wieder einstempel.

Wie stehen die Chancen, dass SmallTime in dem Bereich weiterentwickelt wird?

Viele Grüße
André

**Comment by itmastergmbh** [comment]
Salü André,
Bez. Der Frage zur automatischen Pause.
Das habe ich nur im Programm integriert, weil es viele Firmen gibt, die z.B. 9 Stunden arbeiten und mittags nicht stempeln können (z.B. Bau oder Landschaftsgärtner)
Dann kann man einstellen wie viele Minuten ab einer Arbeitszeitsumme automatisch abgezogen werden sollten. Meistens auch für Firmen die keine Gleitzeit haben.
Wenn die Möglichkeit besteht zu stempeln würde ich unbedingt immer stempeln. (morgens, mittags, nachmittags, abends - > Wie früher bei der Stechuhr.)

Einstellungen :
Pause ab ? Stunden. -> ab wie viel Stempelzeit soll die Automatische Pausenregelung ziehen (bei z. B. 6 Stunden und mehr)
Automatische Pause. - > den Abzug (Beispiel :  30Min = 0.5)

Falls dies nicht gewünscht ist gibt es noch die Möglichkeit die SOLL-Arbeitszeit mit integrierten Pausen einzustellen.
Beispiel:
Sollarbeitszeit eines Mitarbeiters 30 Stunden in der Woche.
Zwingende Pausen 30 Min. pro Tag.
Somit als Wochenarbeitszeit 32.5 Stunden eintragen und nur Morgens und Abends stempeln.

Ich denke, da heute die meisten ein Smartphone haben und mit einem Klick gestempelt werden kann, sollte ein Stempeln eigentlich kein Problem mehr darstellen.
Bei den QR-Codes sehen Sie rot einen Link, den kann man eingeben und es wird gestempelt (rechtsklick auf den roten Text und Adresse kopieren)
Das kann bei jedem Smartphone als Button auf dem Home – Screen erstellt werden.

Viele Grüsse 
Michi

TIPP:
wenn der Time-Server im LAN ist und ein kleiner Access - Point (WLAN) nur für das Stempeln existiert, ist der mit einer Stechuhr vergleichbar. Jeder Mitarbeiter muss sich mit dem WLAN verbinden damit gestempelt werden kann.

**Comment by andre5tz** [comment]
Hallo Michi,
vielen Dank für die ausführliche Rückmeldung. 
Dann müssen wir hier schauen, wie wir das organisatorisch lösen. Ich denke, das Ticket kann ich damit auch schließen.

Viele Grüße
André
