### ISSUE TITLE
Zurück zur Anmeldung

### ISSUE THREAD

**Issue by abry88** [itmastergmbh/SmallTime#33]
Hallo zusammen, 
ich habe SmallTime erfolgreich installiert.
Wenn ich mich nun als Admin anmelde dann kommt auch die Adminoberfläche.
Sobald ich dort eine Schaltfläche betätige springt er wieder zurück ins Anmeldefenster.
Jemand eine Idee ??

**Comment by waja** [comment]
keine Ahnung, ob es da einen Zusammenhang gibt. Aber ich habe seit einige Zeit das Problem, dass ich mich nicht mehr einloggen kann, egal ob Admin-Zugang oder nicht.
Im Inkognito-Modus geht es ohne Probleme. Ich vermute hier ein Problem in Zusammenhang mit Sessions/Cookies.

**Comment by itmastergmbh** [comment]
Hallo zusammen,
ich habe per Zufall mal etwas in den Einstellungen verstellt (nur im Chrome - Browser).
Das habe ich aktivert:
Einstellungen -> Datenschutz Inhaltseinstellungen -> Cookies -> Speicherung von Daten für alle Webseiten 

Dann kam ich immer wieder zurück zum Login.
Lösung: Lokale Daten nach Schliessen des Browsers löschen aktivieren oder die SmallTime - Seite als Ausnahme hinzufügen.
ich hoffe es klappt dann.
