### ISSUE TITLE
Excel Eport zeigt falsche Werte in der "Gearbeitet" Spalte

### ISSUE THREAD

**Issue by Surio89** [itmastergmbh/SmallTime#37]
siehe Titel, siehe Screenshot:
http://pasteboard.co/Bn18f1ZCx.jpg

**Comment by itmastergmbh** [comment]
Ich denk dass kommt von der Einstellung,  ob Punkt oder komma für Zahlen definiert wurde. (umstellen und dann sollte es gehen) Oder  die Felder als Zahl formatieren im Excel sollte auch funktionieren.

**Comment by Surio89** [comment]
Habe mal mit dem Editor in die XLS geschaut. Da steht die richtige Zahl 7.56 was er wohl als 7. 1956 interpretiert. Beim Umstellen des Formats in Excel 2010 wandelt er das Datum dann in die falsche  Zahl um: 20637. Was sich Excel dabei denkt kann ich nicht nachvollziehen. Das wäre nicht mal der passende Timestamp für 7. 1956... Man könnte Excel so einstellen, dass er als Dezimaltrennzeichen den Punkt nutzt aber würde ungern von den Standardeinstellungen abweichen, da es dann Probleme in anderen Dokumenten gibt.

Gibt es dafür eine Einstellung in Smalltime? Habe jetzt die export_xls_monat.php angepasst und der  number_format Funktion ein Komma mitgegeben statt einen Punkt.
