### ISSUE TITLE
Access denied for user images *solution*

### ISSUE THREAD

**Issue by arndtbo** [itmastergmbh/SmallTime#38]
Access denied for user images

*/Data/'yourusers'/img/.htaccess*

```
Order deny,allow
Allow from all
<Files "*">
  	deny from all
 </Files>
Options -Indexes
```

change to

```
Order deny,allow
Allow from all
<Files ~ "\.(jpg)$">
   order deny,allow
   allow from all
</Files>
Options -Indexes
```

**Comment by itmastergmbh** [comment]
Sollte gelöst sein.

**Comment by waja** [comment]
> Order deny,allow Allow from all <Files ~ "\.(jpg)$"> order deny,allow allow from all </Files> Options -Indexes

This is still not compatible to Apache 2.4.

**Comment by arndtbo** [comment]
#Apache 2.4

<FilesMatch "\.(jpg)$">
Order Deny,Allow
    Allow from all
</FilesMatch>

**Comment by arndtbo** [comment]
#Tippfehler!
#Dann so ...

<FilesMatch "\.(jpg)$">
Order Deny,Allow
    Allow from all
</FilesMatch>

**Comment by arndtbo** [comment]
`<FilesMatch "\.(jpg|gif|png)$">
Order Deny,Allow
    Allow from all
</FilesMatch>`

**Comment by waja** [comment]
The issue is: http://httpd.apache.org/docs/2.4/upgrading.html#run-time
