### ISSUE TITLE
Fehler auf der Jahresansicht des Mitarbeiters

### ISSUE THREAD

**Issue by SilvanJ** [itmastergmbh/SmallTime#39]
Bei der Anzeige der Aubezahltenstunden stimmt etwas nicht. 
- Eingabe bei Januar -> keine Anzeige 
- Eingabe bei Dezember -> Anzeige im Januar und Februar und Dezember

Die Summe auf der Jahresansicht für Admin stimmt jedoch. 

![grafik](https://user-images.githubusercontent.com/34896348/34391387-87d1ee66-eb45-11e7-8393-19983c21a085.png)

Ich habe im Code zuwenig durchblick um den Fehler zu erkennen.

Anonsten funktioniert die Software super und mach viel Freude! 
Danke an den Entwickler!

**Comment by itmastergmbh** [comment]
Kleiner Wirkarrohnd... Der hilft im Normalfall.

Jeden Monat ohne Auszahlung eine 0 eintragen.

Dann sollte es gehen.


Am 27. Dezember 2017 20:39:42 schrieb SilvanJ <notifications@github.com>:

**Comment by itmastergmbh** [comment]
V 0.9.019 28.12.2017 -> Fehler in der Auszahlungs - Berechnung - Jahresübersicht - sollte gefixt sein

**Comment by SilvanJ** [comment]
Vielen Dank für den schnellen Update!
Kannst du mir noch sagen, wie ich am Besten das Update auf das produktive System bringe? 
Welche Dateien ersetzen usw.

**Comment by itmastergmbh** [comment]
./Data
./import
./debug
./include/Settings

Die Dateien in den Verzeichnissen vom alten in die neue Version übertragen.
Sollte eigentlich alles sein :)
