### ISSUE TITLE
PHP 7.0

### ISSUE THREAD

**Issue by csaeum** [itmastergmbh/SmallTime#40]
Wann wird es SmallTime für php7 geben bzw wann wird es unter PHP7 laufen?

**Comment by waja** [comment]
Ich habe keine Probleme auf Debian 9 (und PHP 7.0.x), welche auf die PHP Version zurück zu führen sind.

**Comment by csaeum** [comment]
habe es gerade auf einen Raspberry mit libapache2-mod-php7.0 (gibt nichts kleineres) und bekomme immer nur weiße Seite.

In den Logs finde ich auch keine Infos die mich gerade weiterbringen

**Comment by itmastergmbh** [comment]
Ich dachte es sollte unter 7 laufen.
Und welche Meldungen kommen, wenn das Debuging eingeschaltet wird?  (Zeile 32 bei index.php oder admin.php define auf true setzen)

**Comment by csaeum** [comment]
Ich bekomme gerade diese Fehler noch nach einschalten von Debug:

Notice: Undefined index: token in /var/www/html/index.php on line 56
Notice: Undefined index: last in /var/www/html/index.php on line 60
Notice: Undefined index: calc in /var/www/html/index.php on line 102
Notice: Undefined index: designname in /var/www/html/include/class_template.php on line 32
Fatal error: Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/include/class_template.php:47 Stack trace: #0 /var/www/html/index.php(113): time_template->__construct('index.php') #1 {main} thrown in /var/www/html/include/class_template.php on line 47

**Comment by itmastergmbh** [comment]
Das klingt irgendwie wie Dateien fehlen die Einstellungen enthalten.
Schon versucht das Zip von GITHub zu downloaden und nochmals per FTP zu übertragen?

**Comment by csaeum** [comment]
Habe gerade von GitHub per WGET geladen und ins Verzeichniss entpackt.
Nun ist die mit on line 60 weg:

Notice: Undefined index: token in /var/www/html/index.php on line 56

Notice: Undefined index: calc in /var/www/html/index.php on line 102

Notice: Undefined index: designname in /var/www/html/include/class_template.php on line 32

Fatal error: Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/include/class_template.php:47 Stack trace: #0 /var/www/html/index.php(113): time_template->__construct('index.php') #1 {main} thrown in /var/www/html/include/class_template.php on line 47

**Comment by itmastergmbh** [comment]
Ich lade heute Nachmittag das auch mal auf ein Ubuntu mit php7. Ich melde mich wieder.

**Comment by csaeum** [comment]
habe simplexml nun nachinstalliert nun habe ich schonmal das Design vor mir aber mit diesen Meldungen.

Ist das nur weil Debug nun an ist oder sind die Laufzeit relevant?

Notice: Undefined index: token in /var/www/html/index.php on line 56

Notice: Undefined index: calc in /var/www/html/index.php on line 102

Notice: Undefined index: designname in /var/www/html/include/class_template.php on line 32

Notice: Undefined index: admin in /var/www/html/index.php on line 132

Notice: Undefined index: admin in /var/www/html/index.php on line 136

Notice: Undefined index: admin in /var/www/html/index.php on line 137

Notice: Undefined index: lname in /var/www/html/index.php on line 140

Notice: Undefined index: login in /var/www/html/index.php on line 144

Notice: Undefined index: action in /var/www/html/index.php on line 147

Notice: Undefined index: group in /var/www/html/index.php on line 157

Notice: Undefined index: admin in /var/www/html/index.php on line 159

Notice: Undefined index: action in /var/www/html/index.php on line 161

Notice: Undefined index: group in /var/www/html/index.php on line 163

Notice: Undefined index: admin in /var/www/html/index.php on line 175

Notice: Undefined index: login in /var/www/html/index.php on line 236

Notice: Undefined index: tmp in /var/www/html/index.php on line 254

Notice: Undefined index: tmp in /var/www/html/index.php on line 257

Notice: Undefined index: admin in /var/www/html/index.php on line 521

**Comment by itmastergmbh** [comment]
weil das DEBUG noch an ist

**Comment by csaeum** [comment]
Ok danke dann sollte ich nun nur noch das Stempeln hinbekommen über NFC

Danke schonmal kann dann geschlossen werden.
