### ISSUE TITLE
Mitarbeiter xxxx existiert bereits!

### ISSUE THREAD

**Issue by thomasboehm** [itmastergmbh/SmallTime#41]
SMALL - Time Version : 0.9.017
PHP - Version : 7.0.30-1+ubuntu16.04.1+deb.sury.org+1
Memory : 2 MB

Wenn ein Mitarbeiter "test1234" existiert, laesst sich kein neuer Mitarbeiter "test" oder "test12" oder ... anlegen. Scheinbar wird geprueft, ob die die Zeichenkette des neuen Mitarbeiters in der users.txt vorkommt und die Fehlermeldung wird ausgegeben, wenn die Zeichenkette in einem existierenden Nutzer vorhanden ist.

Ich kann leider kein PHP, aber der Fehler sollte in der Funktion user_exist($name) in der Datei include/class_filehandle.php liegen. Vielleicht sollte nicht nach "test", sondern ";test;" gesucht werden, um den Fehler zu vermeiden.

Nachtrag: Manuell laesst sich der MA durch Editieren der users.txt und Erstellen des entsprechenden Verzeichnisses anlegen, jedoch landet der MA "test1234" nach dem Einloggen im Profil des MA "test".

**Comment by itmastergmbh** [comment]
V 0.9.023 08.03.2020 -> Mitarbeiter z.B. test123 und test1234 gefixt
