### ISSUE TITLE
Immer Fehler HTTP ERROR 500

### ISSUE THREAD

**Issue by Chaot1** [itmastergmbh/SmallTime#42]
Ich bekomme immer die Fehlermeldung 
HTTP ERROR 500
wenn ich auf admin oder index zugreifen will.
Die Seite Stempelterminal funktioniert.

Ich habe schon komplett aller Rechte auf 777 gesetzt, aber irgendwie komme ich nicht klar.

**Comment by itmastergmbh** [comment]
Schalten Sie mal die Fehlermeldungen ein in der index.php, admin.php auf Zeile 32 bzw. 33.

define('DEBUG', **true**);

Dann sollten etwas mehr Meldungen erscheinen und hoffe dass dann der Fehler gefunden werden kann.

**Comment by Chaot1** [comment]
Ich bin so Blöd!
Obwohl ich zig mal kontrolliert habe war ich auf PHP 7
Container neu aufgesetzt auf PHP 5 und alles läuft.

Sorry für die Störung

**Comment by AdrianNoss** [comment]
Hallo! Ich hatte auch diese Problem mit Debian und aktuellem PHP7. Einfach das Paket php7.0-xml installieren und den apache neustarten.
