### ISSUE TITLE
Brauche Hilfe beim Umzug

### ISSUE THREAD

**Issue by Chaot1** [itmastergmbh/SmallTime#43]
Ich habe versucht das Verzeichnis komplett auf einen neuen Server umzuziehen.
Klappt nicht.
Wenn ich alle dateien kopiere habe ich zwar alle Daten hier, kann aber die Stempelterminal.php nicht mehr bedienen.
Was mache ich falsch?

**Comment by Chaot1** [comment]
Oh, und gibt es eine Möglichkeit alles upzudaten ohne die User zu verlieren.

**Comment by itmastergmbh** [comment]
Updaten:
neuste Version Downloaden und entpacken und 
./Data
./include/Settings
von der alten Version übernehmen

Bez. Stempelterminal.php bin ich ratlos? Ev. mit F12 mal in der Konsole schauen ob Fehlermeldungen erscheinen?

**Comment by Chaot1** [comment]
Danke schön.
Frage 1 hat sich durch das Update erledigt.
Ich kann auch nicht mehr feststellen an was es gelegen hat.
Kann man eventuell die Updateanleitung in die Installationsanleitung mit aufnehmen?
Ich denke ich bin nicht der Einzige der aus Unwissenheit auf dem alten System bleibt.
