### ISSUE TITLE
Stempelterminal erweitern

### ISSUE THREAD

**Issue by Chaot1** [itmastergmbh/SmallTime#44]
Hallo,
ist es möglich die Seie des Stempelterminals zu erweitern?
Ich kenne mich leider mit PHP absolut nicht aus und wollte hier eigentlich nur einen Verbesserungsvorschlag anbringen der sich bei uns im Laufe des Betriebs ergeben hat:

Die Mitarbeiter würden sich oberhalb der eigentlichen Stempelfelder eine Anzeige von Uhrzeit und Datum wünschen.

Ist sowas umsetzbar?

P.S. 
Absolut geniales Programm das unsere Bedürfnissen (10 Miterbeiter) vollauf abdeckt!

**Comment by itmastergmbh** [comment]
stempelterminal.php - umgesetzt als Beispiel
