### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by karuu** [itmastergmbh/SmallTime#45]
Hello,  i have noticed that your account is inactive for over 3 years. Can you give me your account, please? 
Karu has been my nickname for 16 years and would really appreciate if on my account shared the same nickname. 

Greetings from LA

**Comment by waja** [comment]
I think this is the wrong place trying to get in touch with @karu (which just has a open fork if smalltime).

**Comment by karuu** [comment]
@waja  do you know where i can contact her?

**Comment by waja** [comment]
no

**Comment by karuu** [comment]
Oh noes! OTL
Thanks

**Comment by karu** [comment]
I won't give up my account
