### ISSUE TITLE
Erster Feiertag wird nicht angezeigt

### ISSUE THREAD

**Issue by Babelfisch** [itmastergmbh/SmallTime#46]
Bei den Feiertagen ist mir aufgefallen, dass er erste definierte Feiertag (also nach der Reihenfolge in `$holidays`) in den Einstellungen vom Nutzer nicht angezeigt wird. Habe ich bspw. Deutschland eingestellt, erscheint in der Liste der Feiertage der „Tag der deutschen Einheit“ nicht. Kommentiere ich diesen Tag aus, fällt „Neujahr“ weg.

Nachdem ich ein wenig im Quellcode gewühlt habe, habe ich es mit Änderungen in zwei Dateien beheben können:

In `class_feiertage.php`:

In Zeile 105 den Index von `$x-1` in `$x` geändert: `@$this->_feiertageUSER[$z]` (ansonsten wäre der Index beim ersten Durchlauf auch -1)
Zeile 108 mit `unset($holidays[0]);` gelöscht.

In `class_user.php`:

In Zeile 142 die Schleife von 0 bis < count zählend: `for ($u=0; $u<$_anzahlFT; $u++){`

Damit funktioniert bei mir alles.

**Comment by itmastergmbh** [comment]
Vielen Dank, werde ich überprüfen.
Viele liebe Grüße Michi Heizmann

Am 6. Januar 2020 12:57:08 schrieb Mario Müller <notifications@github.com>:
