### ISSUE TITLE
Erst zu einer bestimmten Zeit einstempeln

### ISSUE THREAD

**Issue by rolbx** [itmastergmbh/SmallTime#47]
Hallo,

wir nutzen SmallTime im Zusammenhang mit einem Raspberry Pi und unsere Arbeitszeit beginnt 06:00 und für manche Mitarbeiter 07:00 Uhr. Eingestempelt wird meistens sofort nach Ankunft am Arbeitsort.

Gibt es eine Möglichkeit bei bestimmten Mitarbeitern die Zeit erst aber einer Vordefinierten Uhrzeit zu setzen?

z.B Mitarbeit stempelt 05:40 und gesetzt werden soll 06:00...

Mit freundlichen Grüßen

**Comment by itmastergmbh** [comment]
Salü,
das ist im moment nicht Möglich.
Viele Grüsse

**Comment by rolbx** [comment]
Hi,

oder wird es irgendwann die Möglichkeit geben alle Zeiten im Browser zu Editieren und nicht jede einzeln per Mausklick?

VG

**Comment by itmastergmbh** [comment]
Salü,
Ist auch nicht in Planung :)
Viele liebe Grüße
