### ISSUE TITLE
PHP 7 ?

### ISSUE THREAD

**Issue by gambur** [itmastergmbh/SmallTime#51]
Ist es möglich das mit einer neuern Version (PHP 7) laufen zu lassen?

Migrator zeigt mir folgende Probleme und ich kriege ein Error 500 in PHP 7

2020-09-17T11:29:29+00:00
Scanning /var/www/time.gambur.ch
Including file extensions: php
Processed 14959 lines contained in 123 files.
Processing took 1.703782081604 seconds.

# critical
#### /var/www/time.gambur.ch/android.php
* variableInterpolation
 * Line 129: `                  }->$_GET['var'];`

#### /var/www/time.gambur.ch/fpdf/fpdf.php
* oldClassConstructors
 * Line 74: `/*  function FPDF($orientation='P', $unit='mm', $size='A4')*/`
* deprecatedFunctions
 * Line 1003: ` if(get_magic_quotes_runtime())`
 * Line 1004: `         @set_magic_quotes_runtime(0);`

#### /var/www/time.gambur.ch/fpdf/makefont/makefont.php
* deprecatedFunctions
 * Line 299: `  if(get_magic_quotes_runtime())`
 * Line 300: `          @set_magic_quotes_runtime(0);`

#### /var/www/time.gambur.ch/include/class_formular.php
* oldClassConstructors
 * Line 85: `   function Formular_old($action, $method) {`

# nuance
#### /var/www/time.gambur.ch/include/class_feiertage.php
* funcGetArg
 * Line 152: `          $args = func_get_args();`

**Comment by ChrisSka** [comment]
Also bei mir läuft es unter PHP 7.4.10 ohne Probleme. Muss wohl an einem anderen Problem/Einstellung liegen.

**Comment by itmastergmbh** [comment]
sollte nun auch mit PHP8 funktionieren
