### ISSUE TITLE
Print to PDF

### ISSUE THREAD

**Issue by djanecic** [itmastergmbh/SmallTime#52]
Hallo,
erstmal Danke für die großartige Arbeit!
Ich bekomme bei aufruf der Druck-Funktion (PDF) jedoch eine Fehlermeldung 500 (Bei der Verarbeitung dieser Anforderung ist ein Fehler aufgetreten), egal auf welcher Ebene. Ist das für jemanden reproduzierbar oder gibt es einen Lösungsansatz?
Die Anwendung läuft auf einem NAS, PHP Version ist 7.3.16.
Danke!

**Comment by AlfMueller** [comment]
Habe auf meiner Synology genau das selbe Problem.
Hast du eine Lösung gefunden?
Danke!

**Comment by djanecic** [comment]
Hallo,
wir haben letztendlich nur die aktuellste Version von GitHub geladen und damit hat es dann auch funktioniert.
Viel Erfolg!
