### ISSUE TITLE
Feiertage zur arbeitszeit zählen

### ISSUE THREAD

**Issue by SerenitysX** [itmastergmbh/SmallTime#53]
Hi, erstmal ganz großes Lob an den Ersteller! Klasse System!

Wäre es möglich die Feiertagsstunden zu den sollstunden und zu den geleisteten stunden + zu rechnen?

Beispiel im Mai diesen Jahres:
3 Feiertage, davon 2 unter der Woche.
Das System gibt mir 152 Sollstunden an wobei es 168 sein müssen

Kann mir da jemand helfen?

**Comment by mrbreil** [comment]
Das ist mir auch aufgefallen. Habt ihr eine Lösung dafür?

**Comment by itmastergmbh** [comment]
In der Klasse class_month.php werden $this->_SummeSollProMonat berechnet.
Weil die Feiertage ja keine Arbeitstage sind, werde die nicht zu den Sollstunden hinzugezählt.
Weil dann in $this->_MonatsArray[$i][8] kein Wert ist (weil das kein Arbeitstag ist) ist da 0 drin.
Ich denke das meint Ihr, dazu müsste function set_monatsdaten etwas umgeschrieben werden.
