### ISSUE TITLE
Fehler in der User-Jahresübersicht

### ISSUE THREAD

**Issue by DKeppi** [itmastergmbh/SmallTime#54]
Hallo!

Seit 2021 stimmt bei mir leider die Jahresübersicht nicht mehr.
Im Jahr 2020 fehlen in der Jahresübersicht plötzlich alle Einträge/Werte, daher ist natürlich auch der Saldo/Übertrag für 2021 falsch...

![image](https://user-images.githubusercontent.com/2063381/103910770-82700d80-5105-11eb-8610-754fe6ede447.png)

Hab bereits in /modules/sites_year/user04_year.php etwas nachgeforscht, aber komme leider nicht auf den Fehler!

Version ist die aktuellste!

Danke für die Hilfe und Grüße in die Schweiz
DKeppi

**Comment by DKeppi** [comment]
Hab mal die Jahresübersicht über den Admin aufgerufen, dort klappts für das einzelne Jahr - beweist dass die Daten da sind ;)

![image](https://user-images.githubusercontent.com/2063381/103911376-3e313d00-5106-11eb-92a2-39c773e680be.png)

**Comment by DKeppi** [comment]
Zusatzinfo:

Habe noch einen User von früher, der von Mitte 2018-Ende 2019 aktiv war. 
Bei diesem User sehen die Jahresübersichten zu 2018 & 2019 korrekt aus!  

Grüße
DKeppi

**Comment by DKeppi** [comment]
Hallo!

Hat keiner eine Idee oder zumindest einen Ansatz wo ich genau suchen könnte und korrigieren muss?

Danke für die Hilfe!

**Comment by bachph** [comment]
In der Jahresübersicht gibt es bei mir ebenfalls ein Problem. Für August und September wird mir jeweils ein Tag Urlaub angezeigt, der aber in der Monatsübersicht nicht existiert. Das verfälscht die Jahresbilanz an Urlaubstagen.

**Comment by itmastergmbh** [comment]
Ist das noch aktuell, denn mit der neusten Version habe ich viele Bereinigt.
Und Tipp: unbedingt Jahresübersicht und Jahresübersicht Detail beide ev. zwei mal öffnen.

**Comment by DKeppi** [comment]
Ja das ist leider auch nach dem Update noch aktuell :(
Die Jahresübersicht Detail funktioniert einwandfrei, die normale Jahresübersicht zeigt aber keine Daten des Vorjahres - vom aktuellen Jahr ist alles da! Kann es an 2020 liegen...alle Jahreszahlen davor und danach passen!

Das Problem habe ich nur bei meinem User der am 1.1.2020 begonnen hat.
Der alte User der von 2018-2019 aktiv war, hat das Problem seltsamerweise nicht!

In den alten Screenshot siehst du das Problem...die sehen nach wie vor so aus ;)

**Comment by itmastergmbh** [comment]
Dann kann es eigentlich nur noch in den Einstellungen vom User liegen, dass das Zeitberechnungsmodell nicht auf kumulierend eingestellt ist, sondern Jährlich. (Alle Summen werden zurückgesetzt auf Ende Jahr) Liege ich damit richtig?  
https://www.small.li/bedienung-fur-admins/mitarbeiter-einstellungen/einstellungen.html

**Comment by DKeppi** [comment]
Ja das stimmt!
Der alte User ist auf kumulierend, der neue auf monatlich.

Bei den Zeiten brauch ich das so, da monatlich die Überstunden auf Null zurückgesetzt werden, nur die Urlaubstage sollen trotzdem jährlich übergeben werden. 

Und in einer Jahresübersicht könnte man ja die Zeiten trotzdem sehen, aber einfach nicht ins nächste Jahr übergeben. Nur die Urlaubstage.

Kann man da etwas machen?

**Comment by itmastergmbh** [comment]
Nein, da fällt mir keinen optimalen Workarround ein.
Ausser der Mitarbeiter würde auch auf kumulierend gestellt und in der 
Auszahlung die minus und Plus Stunden eingetragen bis es monatlich 0 gibt.


Am 29. November 2021 18:20:35 schrieb DKeppi ***@***.***>:

**Comment by DKeppi** [comment]
Schade, aber betrifft ja zum Glück nur die Jahresübersicht! 
In der Zeitenübersicht und in den Summen am linken Rand stimmt alles 😉 Ich werde einfach damit leben, denk ich!

Danke trotzdem!

**Comment by DKeppi** [comment]
Habe jetzt mal umgestellt auf kumulierend, dann passt die Jahresübersicht :)
Ich sehe  in der Zeitenübersicht sogar am linken Rand weiterhin die Monatssumme.

Also ist eigentlich nur die Anzeige zu "Total - Saldo Ende Monat" in meinem Fall irreführend.
Wir würde ich das mit der Auszahlung machen? Das würde ich gerne noch testen.

Danke!

**Comment by itmastergmbh** [comment]
Versuchen Sie diese Anleitung.

https://www.small.li/bedienung-fur-admins/mitarbeiter-einstellungen/auszahlung-von-uberstunden.html


Am 30. November 2021 07:22:42 schrieb DKeppi ***@***.***>:

**Comment by DKeppi** [comment]
Super - danke!
