### ISSUE TITLE
Name bei action=print_month falsche kodierung

### ISSUE THREAD

**Issue by jfrede** [itmastergmbh/SmallTime#55]
Sobald ich auf Drucken klicke steht in meinem Namen "J�rg Frede" bei allen andren actions passt das. 
Da scheint irgendwie die Zeichenkodierung komisch zu sein. 

SMALL - Time Version : 0.9.022
PHP - Version : 7.4.6

**Comment by itmastergmbh** [comment]
Ev. den Namen mal auf oe ändern per WEB und wieder zurück mit ö und nochmal versuchen?

**Comment by itmastergmbh** [comment]
Getestet mit xampp unter Windows, da funktioniert es.
