### ISSUE TITLE
Stempel login

### ISSUE THREAD

**Issue by mrbreil** [itmastergmbh/SmallTime#56]
Vielen Dank erstmal für diese wunderbare Software.
Besteht irgendwie die Möglichkeit die "Schnell Stempel Anmeldung" zu deaktivieren.
Oder könnte ich zu mindestens per CSS "verstecken". Dies würde ich auch gerne mit dem Admin-Login machen, damit ich nur noch eine Anmeldemaske für Mitarbeiter habe. Leider überfordert es manche, wenn zu viele Auswahlmöglichkeiten bestehen. Wenn es nur einen Login gibt, geht dann hoffentlich weniger schief.

**Comment by itmastergmbh** [comment]
Variante 1:
Nehmen Sie das Mulit - Login aus den settings.
Variante 2:
Starten Sie SmallTime so: index.php?group=-1
