### ISSUE TITLE
Auszahlung Überstunden

### ISSUE THREAD

**Issue by mrbreil** [itmastergmbh/SmallTime#57]
Leider habe ich keine Funktion gefunden die mir erlaubt ausgezahlte Überstunden vom Stundenkonto zu entfernen.
Habe ich da was übersehen, oder wie bildet ihr das ab?

**Comment by waja** [comment]
Diese Funktion scheint es nicht zu geben bisher.

**Comment by SerenitysX** [comment]
Hi Leute, ausgezahlte Überstunden könnt ihr in der Jahres Übersicht Details in der Spalte "Ausz." angeben

**Comment by mrbreil** [comment]
Werde es mir anschauen. Danke erstmal
