### ISSUE TITLE
Feiertage Deutschland werden komplett falsch gesetzt

### ISSUE THREAD

**Issue by TCOMSEE01** [itmastergmbh/SmallTime#58]
Folgender Fehler ist bei mir aufgetreten: Die deutschen Feiertage werden nicht entsprechend der ausgewählten Kästchen eingetragen, sondern immer andere als die ausgewählten. Auch ein manuelles anpassen der User txt hat hier nichts gebracht, da die Reihenfolge der 0;1 etc. nicht mit der Reihenfolge der Kästchen übereinstimmt.

**Comment by itmastergmbh** [comment]
Sollte nun funktionieren.
