### ISSUE TITLE
htaccess

### ISSUE THREAD

**Issue by gitschwarz** [itmastergmbh/SmallTime#59]
mit dem Update von apache sollte die htaccess zukünftig so aussehen
<Files ~ "^\.(htaccess|htpasswd)$">
        deny from all
        <IfVersion < 2.3>
          Order allow,deny
          Require all denied
        </IfVersion>

</Files>
<Files "*.txt">
        deny from all
        <IfVersion < 2.3>
          Order allow,deny
          Require all denied
        </IfVersion>

 </Files>
Options -Indexes
order deny,allow

(sorry für den Mißbrauch  des Issues - git verwende ich nur als normaler User und bin mit den Uploadmechanismen nicht sonderlich vertraut)

**Comment by itmastergmbh** [comment]
thx
