### ISSUE TITLE
Zeit eintragen mit "über MItternacht gearbeitet wurde"

### ISSUE THREAD

**Issue by geraldurbas** [itmastergmbh/SmallTime#60]
Cooles Ding - da klappt ganz viel ziemlich gut!

Wenn vom Vortag noch eine Endzeit fehlt, fragt das Popup nach ob "über MItternacht gearbeitet wurde"
![image](https://user-images.githubusercontent.com/121263/139723437-879d850b-6907-4c4c-9383-517d7a3c2e19.png)

Rauskommt dan aber ff:
![image](https://user-images.githubusercontent.com/121263/139723523-7405c1b6-2746-4add-97b5-e287aa1bfa05.png)

-> Korrekt wäre meines Erachtens:
- Abfrage bis zu welcher Uhrzeit am Folgetag gearbeitet wurde:
Dan eintragen "23:59" am 1.11 eintragen und
und der fehlende Zeitraum (zb. am 2.11.21 von 0:00 - 02:00) eintragen.

Als ich dan nochmal "Zeit hinzufügen" geklickt hab hat er dan 23:59 als Anfang genommen
und nochmal "Zeit hinzufügen" geklickt da war dann offenbar die Anfangszeit  19:42 als Anfang genommen

![image](https://user-images.githubusercontent.com/121263/139724407-82f89b35-0584-4e72-91d9-e247c90bb2a6.png)

Das kann man also zwar korrigieren, aber kann doch auch zu heftigen Fehlern führen wenn man sich drauf verlassen möchte!

**Comment by itmastergmbh** [comment]
Danke, ich denke dass irgendwo ein Rundungsfehler im Code das Problem verursacht, ich muss dem auf den Grund gehen.

**Comment by itmastergmbh** [comment]
Gerade mit der neusten Version geprüft. Bei der Auswahl über Nacht, wird bei mir 24:00 eingetragen.
(xampp / windows)

**Comment by geraldurbas** [comment]
Bestätigt - mit der aktuellsten Version funktioniert das! mercy
