### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by franzpro** [itmastergmbh/SmallTime#62]
Hallo,

ich habe den SmallTime Ordner auf einen neuen Server verschieben müssen.
(Neuer Server Apache 2.2 und PHP 7.4 / 
Alter Server Apache 2.2 /PHP 7.0) 

Und erhalten sehr viele Fehler die ungefähr so lauten:

`Warning: A non-numeric value encountered in /volume1/web/small/include/class_month.php on line 221 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 290 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 293 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 290 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 293 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 290 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 293 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 290 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 293 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 290 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 293 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 290 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 293 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 290 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 293 Warning: A non-numeric value encountered in /volume1/web/small/include/class_jahr.php on line 290`

usw.... 

Kann mir jemand einen Tipp geben wo ich suchen muss ? Kann das an der php-xml Extension liegen? Die sollte eigentlich laufen. 

vielen Dank vorab

Franz

**Comment by itmastergmbh** [comment]
Welche Version von Small Time?
Ich denke mit der neusten sollte es keine Probleme diesbezüglich geben.

**Comment by franzpro** [comment]
Hallo,

ich hatte die Version ganz frisch von Github genommen. Jetzt habe ich einfach die Migration nochmal durchgeführt und es hat geklappt. Allerdings habe ich ein paar Kleinigkeiten nicht so gemacht, wie in der Update Anleitung in Github steht.

> Update einer alten Version

    Ordner der alten Version umbenennen (z.B. /time -> /time_old)
    neue Version installieren (Ordner wie früher benennen /time)
    Schreibrechte auf Ordner setzen in der neuen Version
    **./include/Settings -> Dateien der alten Version in die neue kopieren** 
    ./Data -> alle Ordner und Dateien der alten Version in die neue kopieren


In dem Settings Ordner habe ich nicht alle Dateien genommen, sondern nur 
- feiertage.txt, pausen.txt, zuschlag.txt und settings.txt. 

Den Rest habe ich von der neueren Version gelassen. Gerade in der smalltime.txt steht die Versionsnummer. Diese wird dann immer mit der alten Version überschrieben, was recht blöd ist.

Ich weiß nicht, ob das der Grund war, aber dann hat es funktioniert mit der Migration.

Vielen Dank und schöne Grüße

Franz
