### ISSUE TITLE
Probleme mit PHP 8.0

### ISSUE THREAD

**Issue by DKeppi** [itmastergmbh/SmallTime#68]
Hallo,

Synology hat endlich PHP 8.0 released - leider klappt Smalltime damit nicht

Habe auch schon eine komplette Neuinstallation versucht, bekomme immer HTTP ERROR 500 und eine leere Seite. 
Zum Login komme ich noch, aber danach ist es vorbei.

Chrome und Edge melden in den Entwicklertools nur " (Index):6772 crbug/1173575, non-JS module files deprecated."

**Comment by waja** [comment]
Kann ich (auch für PHP 8.1) bestätigen. Falls hier Logs oder eine Demoumgebung gebraucht werden, gern melden. Ich kann schnell einen vHost mit Master irgendwohin werfen.

**Comment by itmastergmbh** [comment]
Hi, leider habe ich keine Synology mit php8.
Aber was kommt, wenn man Debugging einschaltet (also Fehlermeldungen anzeigen lässt)
admin.php -> Zeile35 : define('DEBUG', true);
Dann sollten die Fehlermeldungen erscheinen.

**Comment by DKeppi** [comment]
Hi

Danke für die Info bzgl. DEBUG, das kannte ich gar nicht!

Nach dem Admin Login kommt:

`Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /volume1/web/smalltime/include/class_month.php on line 75 TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /volume1/web/smalltime/include/class_month.php on line 75 Call Stack: 0.0015 544616 1. {main}() /volume1/web/smalltime/admin.php:0 0.0754 1638792 2. time_month->__construct($SettingCountry = '3', $lastday = 31, $ordnerpfad = 'administrator', $jahr = '2022', $monat = '8', $arbeitstage = [0 => '0', 1 => '1', 2 => '1', 3 => '1', 4 => '1', 5 => '1', 6 => '0\r\n'], $ufeiertag = [0 => '1', 1 => '1', 2 => '0', 3 => '0', 4 => '1', 5 => '0', 6 => '1', 7 => '1', 8 => '1', 9 => '1', 10 => '1', 11 => '1', 12 => '1', 13 => '1', 14 => '0', 15 => '0', 16 => '0', 17 => '0', 18 => '0', 19 => '0', 20 => '1', 21 => '1', 22 => '1', 23 => '0\r\n'], $_SollProTag = 8, $_startzeit = '4070905200\r\n', $arbeitszeit = '', $autopause = '', $absenzberechnung = '1', $absenzberechnungArbeitszeit = '1') /volume1/web/smalltime/admin.php:650 0.0768 1649144 3. time_month->absenzsetting() /volume1/web/smalltime/include/class_month.php:63`

**Comment by itmastergmbh** [comment]
Kann es sein, dass Du eine ältere Version benutzt? Denn ich dachte die Fehler (welche mit php 8 kommen) habe ich gefixt.
Früher war der Fehler in der Datei auf Zeile 75.
Dann habe ich das gefixt
if (is_array($this->_absenz->_array)) {.....
Ist glaub jetzt auf Zeile 85 in der Datei, weil noch mehr geändert werden musste. 

Mit der neusten Variante hoffe ich klappt es.

**Comment by DKeppi** [comment]
Hatte tatsächlich noch eine alte class_month.php

Der Tipp mit dem Debug hat mich auch noch zu anderen Dingen geführt die ich fixen konnte.
Aktuell bleibt nur noch das Problem, dass in der Jahresübersicht alle Zeiten auf 0 bleiben...

**Comment by itmastergmbh** [comment]
DEBUG verhindert bei SmallTime ja nur die Ausgabe von Fehlermeldungen. 

define('DEBUG', false);
if (DEBUG == true) {
	error_reporting(E_ALL);
	//error_reporting(E_ALL ^ E_NOTICE);
	ini_set("display_errors", 1);
} else {
	error_reporting(0);
	ini_set("display_errors", 0);
}

**Comment by DKeppi** [comment]
hab dann noch die fpdf.php ausgetauscht und das wars dann auch :)
