### ISSUE TITLE
Lizenz ist nicht vermerkt

### ISSUE THREAD

**Issue by rbircher** [itmastergmbh/SmallTime#69]
Hallo zusammen

Es reicht leider nicht aus, Auf der Homepage zu erwähnen, dass das Projekt als Open Source verbreitet wird. Denn

1. Ist Open Source keine Lizenz, es gibt viele Lizenzen die unter Open Source laufen.
2. Muss die Lizenz korrekt erwähnt sein.

Das hört sich jetzt nach Bünzlischwiizer an. So fehlt aber die rechtliche Sicherheit, die Lizenzen wie GPL, Apache License v.2, oder MIT License bieten.

Ich bin bereit zu helfen, dies zu ändern.

Gruss Raphael

**Comment by itmastergmbh** [comment]
Salü Raphael,
stimmt vollkommen, wollte ich schon lange ändern.
Ich glaube das korrekte wäre: CC-BY-NC-SA-4.0
Viele Grüsse Michi

**Comment by rbircher** [comment]
Hallo

Bist du dir sicher, dass du das NC drin haben möchtest. NC = Non Commercial. Das heisst, man kann die Zeiterfassung auch nicht für Firmen benutzen.

Gruss Raphael

**Comment by itmastergmbh** [comment]
Ja, weil ohne NC das Werk verändert werden und danach kommerziell vertrieben werden könnte.

NC  bedeutet meines Wissens: Zitat:
_Die NonCommercial (NC)-Lizenzen von CC verbieten Verwendungen, die „in erster Linie für kommerzielle Vorteile oder finanzielle Entschädigungen bestimmt oder darauf ausgerichtet sind“._
https://creativecommons.org/faq/#does-my-use-violate-the-noncommercial-clause-of-the-licenses

Fazit: anwenden dürfen die Firmen Intern die Software (ist nicht in erster Linie kommerziell). Wenn z.B. eine Firma SmallTime hosten würde und das dann Kunden verrechnen würde, das ginge nicht. 

Sehe ich schon richtig nehme ich an, lasse mich aber gerne des besseren belehren.
Grüsse Michi

**Comment by rbircher** [comment]
Das Kernproblem des NC's ist, dass es (bewusst) nicht genau definiert ist. Was Kommerziell ist und was nicht, wird ziemlich offen gelassen. Es heisst, man solle im Zweifel den Lizenzgeber kontaktieren. Man kann sehr wohl die Anwendung in einer Firma als kommerziell ansehen.

Zudem ist die CC Lizenz bei Software relativ unüblich.

Die AGPL zum Beispiel verhindert zwar nicht, dass andere Small Time hosten, zwingt aber die Betreiber dazu ihre Änderungen wieder dem öffentlich zu machen. Davon kann auch das Projekt profitieren.

Gruss Raphael

**Comment by itmastergmbh** [comment]
Stimmt, APGL passt auch....... nehme den Standard Text der Github da integriert  :)
Ich glaub das passt. thx

**Comment by rbircher** [comment]
Sehr gut... Ich gehe davon aus, du hast Interesse an Code Verbesserungen, oder?

**Comment by itmastergmbh** [comment]
Verbesserungen, klar, wobei ich es heute nicht mehr so umsetzten würde. Das Projekt war ursprünglich nur ein Beispiel für ein Kurs - in csv-Dateien schreiben und lesen, und ist in den 15 Jahren halt etwas gewachsen. Es hat auch noch ganz viele Altlasten.
