### ISSUE TITLE
Ich kann bestimmten Mitarbeiter nicht mehr bearbeiten

### ISSUE THREAD

**Issue by Chaot1** [itmastergmbh/SmallTime#70]
Ich habe vor ein paar Wochen einen Mitarbeiter mit der Usernummer 4 bearbeitet unter 
/admin.php?action=show_time&admin_id=4
dabei ist irgendwas abgestürzt.
Danach habe ich diesen Mitarbeiter entfernt und am Ende neu angehängt.
Jetzt kann ich erneut den Mitarbeiter der jetzt die Nummer 4 hat nicht aufrufen.

**Comment by itmastergmbh** [comment]
Hi.
Es gibt zwei Dateien und Ordner die kontrolliert werden können:
Mit jedem Editor können die txt - Files bearbeitet werden.

FILE: **Data/user.txt** 
`
**Pfad**;Name;Passwort in sha1;Gruppe;RFID
**administrator**;admin;7110eda4d09e062aa5e4a390b0a572ac0d2c0220;
**HansMuster**;hamu;7110eda4d09e062aa5e4a390b0a572ac0d2c0220;
`
Möglich Fehler: leere Zeile in der Datei. Pfad stimmt nicht. Name ist doppelt vorhanden.

FILE: **Data/group.txt**
`
1;Administratoren;1
2;Mitarbeiter;1,2
`
Mögliche Fehler: Mitarbeiter-ID ist nicht in der Gruppe

ORDNER : **Data/HansMuster**
Der Pfad in der user.txt muss identisch sein mit dem Ordnernamen (LINUX: Case Sensitive).

Falls in der user.txt der Pfad korrekt ist, der Ordner vorhanden ist und die default - Ordner und Files da auch drin sind (können z.B. von einem andern User kopiert werden), dann sollte auch ein Login möglich sein.
