### ISSUE TITLE
Arbeitszeit, Pausenzeit, Sonderzeiten

### ISSUE THREAD

**Issue by WeT-Klb** [itmastergmbh/SmallTime#72]
Hallo,

ich habe folgende Frage:
Wenn ich z.B. um 6:43 kommend und 15:01 gehend buche, rechnet das System eine Anwesendheitszeit von 8:30 in Industrieminuten.
Allerding wird eine Pause nicht abgezogen und ich erhalte eine Saldozeit von 0.70 Minuten.
Eigentlich sollten nach 6 Stunden 0,50 (30) Minuten und nach 9 Stunden 0.25 (15) Minuten abgezogen werden - so daß hier das Saldo 0.20 Minuten lauten müsste..
Läßt sich das realisieren? Im Idealfall als "einschleifende" Pausen - soll heißen, nach 6 Stunden wird die Arbeitszeit für 30 Minuten nicht weiterberechnet (in diesem Beispiel 12:43 bis 13:13).
![Small 1](https://user-images.githubusercontent.com/20600342/190121943-556f9d80-2cc9-44eb-8c10-87c938bd0742.jpg)
![Small 2](https://user-images.githubusercontent.com/20600342/190121985-c2a72343-7b9e-4db5-a461-91f6d30d5431.jpg)

2. Frage:
Ist es möglich, Sonderzeiten zu hinterlegen? Da wir Desksharing nutzen und täglich den Arbeitsplatz vorbereiten müssen, erhalten wir 2x am Tag je 0.08 Minuten Zeitzuschlage auf unsere Arbeitszeit.
Um in diesem Beispiel zu bleiben, wäre für mich richtig:
Anwesendheitszeit 8.30 - Pause 0.50 Minuten + Zeitzuschlag 2x 0.08 Minuten = Saldo 0.36 Minuten.

3. Frage
In der Liste der Feiertage fehlt der 6. Januar - läßt sich dieser nur über "Settings" erzeugen?
=> LÖSUNG:
In der Datei /small/include/class_feiertage.php (bei mir Zeile 177) die bestehenden Feiertage so erweitern:
$holidays['Heilige 3 K&ouml;nige'] = mktime(0, 0, 0, 1, 6, $year);

MfG
Werner Tröger

**Comment by WeT-Klb** [comment]
Zu Frage 1:
Bei uns ist es so, daß nach 6 Stunden automatisch eine 30minütige Pause "eingeschleift wird - also nach 6 Stunden wird für 30 Minuten keine Arbeitszeit weitergezählt.
Das gleiche Spiel passiert nach 9 Stunden mit einer 15minütigen Pause.
Das heißt, ich darf am Tag maximal 10Std45min anwesend sein (Maximale Arbeitszeit 10 Stunden plus Pause 45 Minuten).
Für das System bedeutet das, daß es unerheblich ist, ob ich um 12:01 oder oder12:30 gehe, wenn ich um 6 Uhr komme.
Wie sage ich dem System, daß es 2 Pausen abhängig von der Anwesendheitsdauer gibt?

Zu Frage 2:
Das muß ich mal testen

Zu Frage 3:
Da hab ich ja schon eine für mich funktionierende Lösung gefunden.

**Comment by itmastergmbh** [comment]
Das heisst, wenn jemand zwischen 6 und 9 Stunden arbeitet, sollen 30 Minuten abgezogen werden.
Von 9 Stunden und mehr 15 Minuten,
![image](https://user-images.githubusercontent.com/6435657/205275915-9b1fc5d6-d129-4229-9cd1-5b5cb5b3a935.png)

Würde dann heissen (TIPP: mit der Maus über den Wecker mit der Pause fahren, dann werden Informationen angezeigt)
![image](https://user-images.githubusercontent.com/6435657/205276025-e22bb207-5ec3-4311-ad79-733ca7af9cb2.png)

**Comment by WeT-Klb** [comment]
Ah perfekt - das funktioniert. Ich wußte nur nicht, wie ich das definieren muß.

Jetzt fehlt mir nur noch Frage 2.
Ich habe versucht, eine dritte Pause von 1 - 10 Stunden mit -0.16 (zwei mal 0.08 bzw. 5 Minuten) anzugeben - aber da beschwert sich das System:

![Small1](https://user-images.githubusercontent.com/20600342/205281826-487d756c-e424-42f1-85a2-8c45691e1434.jpg)

**Comment by itmastergmbh** [comment]
Überschneidungen von Pausenregelungen können nicht definiert werden.
ID 1 geht so bei Ihnen nicht. Es ist nur eine Pause pro Zeitspanne definierbar!

Problem 2: es können keine Ausnahmen definiert werden einer Pausenregelung wie gewüscht. (das heisst: wenn eine Arbeitszeit z.B. 7 Stunden wäre, dass 0.5 abgezogen wird, aber wenn um 12 Uhr ausgestempelt wird, dann darf die 0.5 nicht abgezogen werden -ausnahme beim Stempeln zwischen ....), ist auch nicht vorgesehen.

Vorschlag: lassen Sie immer stempeln. Auch Pausen sollen gestempelt werden. Dann erübrigt sich das Gaze. (das machen wir so) dann könnte das mit -0.16 auch funktionieren

**Comment by WeT-Klb** [comment]
Alles klar - ich habe mich nur gefragt, ob es vielleicht nur eine Definitionssache der Pausenzeiten ist.
Bei uns wird halt nur Kommen und Gehen gestempelt und die Pausenzeiten errechnen sich automatisch.
Ich wollte das nur als Kontrollmöglichkeit nutzen.

**Comment by itmastergmbh** [comment]
Kein Problem :)
Als Kontrollmöglichkeit wäre ev. Excel auch zu gebrauchen?
So in der Art: https://www.it-master.ch/files/SMALL-TIME-EXCEL-LITE.xlsx
