### ISSUE TITLE
Stempelzeiten die in der Zukunft liegen verhindern

### ISSUE THREAD

**Issue by bullyxy** [itmastergmbh/SmallTime#75]
Hallo,

ist es möglich zu verhindern, dass Mitarbeiter Zeiten in der Zukunft eintragen können? Sprich, es soll nicht möglich sein um 15:55 Uhr einen Zeitstempel für 16:00 Uhr zu setzen.
Gibt es eine Möglichkeit so ein Verhalten zu konfigurieren oder ist geplant sowas umzusetzen?

**Comment by itmastergmbh** [comment]
Nein,
wobei.....
wird in den Settings eingestellt, dass ein MA die Zeiten nicht editieren darf, eine Zeit hinzufügen verboten wird und auch mehrere Zeiten nicht eingefügt werden können, dann kann der Mitarbeiter nur noch über QuickTime die aktuelle Zeit einfügen.

https://www.small.li/bedienung-fur-admins/settings-einstellungen/einstellungen.html
